HrManagementTool.WebApp/Models/ErrorViewModel.cs
using System;

namespace HrManagementTool.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HrManagementTool.WebApp/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HrManagementTool.WebApp.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }
        
        [Required]
        public string Password { get; set; }
    }
}

HrManagementTool.WebApp/Models/UserViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using HrManagementTool.BLL.DTOs;

namespace HrManagementTool.WebApp.Models
{
    public class UserViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string SecondName { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
        [Range(1, Int32.MaxValue, ErrorMessage = "Please specify position")]
        public int PositionId { get; set; }
        public bool IsEdit { get; set; }
    }
}

HrManagementTool.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HrManagementTool.WebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace HrManagementTool.WebApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

HrManagementTool.WebApp/Controllers/PositionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using HrManagementTool.BLL.DTOs;
using HrManagementTool.BLL.Services;
using System.Collections.Generic;
using JqueryDataTables.ServerSide.AspNetCoreWeb;

namespace HrManagementTool.WebApp.Controllers
{
    [Authorize]
    public class PositionController : Controller
    {
        private readonly PositionService _positionService;

        public PositionController(PositionService positionService)
        {
            _positionService = positionService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Load([FromQuery] DTParameters parameters)
        {
            List<PositionDto> positions = _positionService.GetPositionList(parameters.Start + 1, parameters.Length);
            
            int count = _positionService.GetPositionCount();

            return new JsonResult(new DTResult<PositionDto>() {
                draw = parameters.Draw,
                data = positions.ToArray(),
                recordsTotal = count,
                recordsFiltered = count
            });
        }
    }
}

HrManagementTool.WebApp/Controllers/ProfileController.cs
namespace HrManagementTool.WebApp.Controllers
{
    public class ProfileController
    {
        
    }
}

HrManagementTool.WebApp/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using HrManagementTool.WebApp.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace HrManagementTool.WebApp.Controllers
{
    public class SecurityController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromForm] LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Invalid username or password");
                return View(model);
            }
            
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, model.Username)
            };
            
            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(principal: principal, scheme: CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }
    }
}

HrManagementTool.WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using HrManagementTool.BLL.DTOs;
using HrManagementTool.BLL.Services;
using HrManagementTool.Domain;
using HrManagementTool.WebApp.Models;
using JqueryDataTables.ServerSide.AspNetCoreWeb;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HrManagementTool.WebApp.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserService _userService;
        private readonly PositionService _positionService;

        public UserController(UserService userService, PositionService positionService)
        {
            _userService = userService;
            _positionService = positionService;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Load([FromQuery] DTParameters model)
        {
            List<UserDto> users = _userService.GetUsers(model.Start + 1, model.Length);
  
            int c = _userService.GetUserCount();
            var result = new DTResult<UserDto>
            {
                draw = model.Draw,
                data = users.ToArray(),
                recordsTotal = c,
                recordsFiltered = c
            };
 
            return new JsonResult(result);
        }

        
        public IActionResult Create()
        {
            ViewBag.positions = _positionService.GetPositionList();
            
            return View(new UserViewModel());
        }

        [HttpPost]
        public IActionResult Create([FromForm] UserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Some fields are missing or invalid");
                ViewBag.positions = _positionService.GetPositionList();
                
                return View(model);
            }
            
            _userService.Create(new UserDto()
            {
                Username = model.Username,
                CreateAt = model.CreatedAt,
                FirstName = model.FirstName,
                IsActive = model.IsActive,
                SecondName = model.SecondName,
                Position = _positionService.GetOne(model.PositionId),
                PasswordHash = _userService.EncryptPassword(model.Password)
            });

            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult Edit(int id)
        {
            UserDto user = _userService.GetOne(id);
            
            ViewBag.positions = _positionService.GetPositionList();
            
            return View(new UserViewModel()
            {
                CreatedAt = user.CreateAt,
                FirstName = user.FirstName,
                IsActive = user.IsActive,
                PositionId = user.Position.Id,
                SecondName = user.SecondName,
                Username = user.Username,
                IsEdit = true
            });
        }

        [HttpPost]
        public IActionResult Edit([FromForm] UserViewModel model)
        {
            Console.WriteLine(JsonConvert.SerializeObject(model));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int id)
        {
            _userService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HrManagementTool.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @{
        if (@User.Identity.IsAuthenticated)
        {
            <p>@User.Identity.Name</p>
        }
    }
</div>

HrManagementTool.WebApp/Views/Position/Index.cshtml
<h1>Hello world</h1>

HrManagementTool.WebApp/Views/Security/Login.cshtml
@model LoginViewModel;
@{
    Layout = "";
}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Login</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <style>
        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        li {
            text-align: center;
            vertical-align: center;
        }
    </style>
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">HR+</h1>
            </div>
            <h3>Welcome to HR+</h3>
            <p>Login in. To see it in action.</p>
            
            <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
            
            <form class="m-t" method="post" asp-controller="Security" asp-action="Login">
                <div class="form-group">
                    <input type="text" class="form-control" asp-for="Username" placeholder="Username" required="" />
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" asp-for="Password" placeholder="Password" required="" />
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>
            </form>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.js"></script>

</body>

</html>

HrManagementTool.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HrManagementTool.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HrManagementTool.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HrManagementTool.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

HrManagementTool.WebApp/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewData["Title"]</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    
    @RenderSection("Styles", required: false)

</head>

<body class="top-navigation">
    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom white-bg">
        <nav class="navbar navbar-expand-lg navbar-static-top" role="navigation">
            <!--<div class="navbar-header">-->
                <!--<button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">-->
                    <!--<i class="fa fa-reorder"></i>-->
                <!--</button>-->

                <a class="navbar-brand" asp-controller="Home" asp-action="Index">HR+</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-reorder"></i>
                </button>

            <!--</div>-->
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav mr-auto" id="nav-menu">
                    <li class="active">
                        <a asp-controller="Home" asp-action="Index">My Profile</a>
                    </li>
                    <li>
                        <a asp-controller="User" asp-action="Index">Users</a>
                    </li>
                    <li>
                        <a aria-expanded="false" role="button" href="layouts.html">Requests</a>
                    </li>
                    <li>
                        <a aria-expanded="false" role="button" href="layouts.html">Reasons</a>
                    </li>
                    <li>
                        <a asp-controller="Position" asp-action="Index">Positions</a>
                    </li>
                </ul>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a asp-controller="Security" asp-action="Logout">
                            <i class="fa fa-sign-out"></i> Log out (@User.Identity.Name)
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        </div>
        <div class="wrapper wrapper-content">
            <div class="container">
                @RenderBody()
            </div>
        </div>
        <div class="footer">
            <div>
                <strong>Copyright</strong> Alexander Andreiev &copy; 2014-2018
            </div>
        </div>

        </div>
        </div>



    <!-- Mainly scripts -->
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/js/inspinia.js"></script>
    <script src="~/js/plugins/pace/pace.min.js"></script>

    <!-- Peity -->
    <script src="~/js/plugins/peity/jquery.peity.min.js"></script>
    <!-- Peity demo -->
    <script src="~/js/demo/peity-demo.js"></script>
    
    @RenderSection("Scripts", required: false)

</body>

</html>

HrManagementTool.WebApp/Views/User/Create.cshtml
@{
    ViewData["Title"] = "Create User";
}

<partial name="_UserForm" model="@Model"/>

@section Styles
{
    <partial name="_UserStyles"/>
}

@section Scripts
{
    <partial name="_UserScripts" />
}

HrManagementTool.WebApp/Views/User/Edit.cshtml
@{
    ViewData["title"] = "Edit User";
}

<partial name="_UserForm"/>   

@section Styles
{
    <partial name="_UserStyles"/>
}

@section Scripts
{
    <partial name="_UserScripts" />
}

HrManagementTool.WebApp/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Users";   
}

<div class="row">
    <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>Users</h5>
                
                <div class="ibox-tools">
                    <a asp-controller="User" asp-action="Create" class="btn btn-primary" style="margin-top: -8px">Create</a>        
                </div>
            </div>
            <div class="ibox-content">    
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="user-dataTable">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Username</th>
                            <th>First name</th>
                            <th>Second name</th>
                            <th>Is active</th>
                            <th>Created At</th>
                            <th>Position</th>
                            <th>Edit</th>
                            <th>Remove</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles
{
    <link href="~/css/plugins/dataTables/datatables.min.css" rel="stylesheet">
}

@section Scripts
{
    <script src="~/js/plugins/dataTables/datatables.min.js"></script>
    <script src="~/js/plugins/dataTables/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/moment/moment.min.js"></script>
    
    <script src="~/app/user.dt.js"></script>
}

HrManagementTool.WebApp/Views/User/_UserForm.cshtml
@model UserViewModel;

<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5>@ViewData["title"]</h5>
                <div class="ibox-tools"></div>
            </div>
            <div class="ibox-content">
                <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
                <form method="post" asp-controller="User" asp-action="@(Model.IsEdit ? "Edit" : "Create")">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Username</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="Username"/>
                        </div>
                    </div>
                    @if (!@Model.IsEdit)
                    {
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Password</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" asp-for="Password"/>
                            </div>
                        </div>   
                    }
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">First name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="FirstName"/>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Second name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="SecondName"/>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Ia active</label>
                        <div class="col-sm-10">
                            <div class="i-checks">
                                <label class="">
                                    <div class="icheckbox_square-green" style="position: relative;">
                                        <input type="checkbox" asp-for="IsActive" style="position: absolute; opacity: 0;">
                                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                    </div>
                                    <i></i>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row" id="data_1">
                        <label class="col-sm-2 col-form-label">Created at</label>
                        <div class="col-sm-10">
                            <div class="input-group date">
                                <span class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </span>
                                <input type="text" class="form-control" asp-for="CreatedAt"/>
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Position</label>
                        <div class="col-sm-10">
                            <select asp-for="PositionId" class="form-control m-b" asp-items="@(new SelectList(ViewBag.positions, "Id", "Title"))">
                                <option selected="selected" value="0">Choose position</option>
                            </select>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

HrManagementTool.WebApp/Views/User/_UserScripts.cshtml
<script src="~/js/plugins/datapicker/bootstrap-datepicker.js"></script>
<script src="~/js/plugins/iCheck/icheck.min.js"></script>
<script type="text/javascript">
    $(document).ready(() => {
        $('#data_1 .input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true,
            format: "yyyy-mm-dd"
        });
    
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
    });
</script>

HrManagementTool.WebApp/Views/User/_UserStyles.cshtml
<link href="~/css/plugins/datapicker/datepicker3.css" rel="stylesheet">
<link href="~/css/plugins/iCheck/custom.css" rel="stylesheet">
<style>
    ul {
        list-style: none;
        padding: 0;
        margin: 0;
    }
    li {
        text-align: center;
        vertical-align: center;
    }
</style>